language: python
python:
  - "3.5"
services:
  - postgresql
  - redis-server
install:
  - pip install -r requirements.txt
  - pip install coverage
script:
  - python manage.py check
  - coverage run --source='.' --omit='*/migrations/*' manage.py test
after_success:
  - coverage report