# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 16:08
from __future__ import unicode_literals

import colorful.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_notifications', models.BooleanField(default=True)),
                ('hourly_notifications', models.BooleanField(default=False)),
                ('news_emails', models.BooleanField(default=True)),
                ('colour', colorful.fields.RGBColorField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userware', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
