# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 17:43
from __future__ import unicode_literals

import colorful.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nyuuustead.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nyuuustead', '0003_auto_20160707_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_colour', colorful.fields.RGBColorField(colors=('#1b85b8', '#03c03c', '#559e83', '#ae5a41', '#c3cb71', '#c23b22', '#ffb347', '#f49ac2', '#dea5a4', '#e3e387', '#77dd77', '#b19cd9', '#ffd1dc', '#779ecb', '#cb99c9', '#966fd6'), default=nyuuustead.models.best_colour)),
                ('target_colour', colorful.fields.RGBColorField(colors=('#1b85b8', '#03c03c', '#559e83', '#ae5a41', '#c3cb71', '#c23b22', '#ffb347', '#f49ac2', '#dea5a4', '#e3e387', '#77dd77', '#b19cd9', '#ffd1dc', '#779ecb', '#cb99c9', '#966fd6'), default=nyuuustead.models.best_colour)),
                ('kind', models.CharField(choices=[('hug', 'hugged'), ('cuddle', 'cuddled'), ('embrace', 'embraced')], db_index=True, default=nyuuustead.models.best_hug, max_length=30)),
                ('inspiration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kids', to='nyuuustead.Hug')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hugs_given', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hugs_gotten', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pronoun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('object', models.CharField(max_length=20)),
                ('possessive_determiner', models.CharField(max_length=20)),
                ('possessive_pronoun', models.CharField(max_length=20)),
                ('reflexive', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='userware',
            name='colour',
            field=colorful.fields.RGBColorField(colors=('#1b85b8', '#03c03c', '#559e83', '#ae5a41', '#c3cb71', '#c23b22', '#ffb347', '#f49ac2', '#dea5a4', '#e3e387', '#77dd77', '#b19cd9', '#ffd1dc', '#779ecb', '#cb99c9', '#966fd6'), default=nyuuustead.models.best_colour),
        ),
    ]
