# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nyuuustead', '0005_userware_pronoun'),
    ]

    operations = [
        migrations.CreateModel(
            name='HugKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('past', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(model_name='hug', name='kind'),
        migrations.AddField(
            model_name='hug',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hugs', to='nyuuustead.HugKind'),
        ),
    ]
