# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyuuustead', '0006_auto_20160707_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hugkind',
            name='name',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
