# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nyuuustead', '0007_auto_20160707_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='userware',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userware',
            name='pronoun',
            field=models.ForeignKey(help_text="Is your pronoun missing? Shoot an email at michcioperz@gmail.com and we'll look into it!", on_delete=django.db.models.deletion.CASCADE, related_name='pronouns', to='nyuuustead.Pronoun'),
        ),
    ]
