# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nyuuustead', '0008_auto_20160707_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hug',
            name='inspiration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kids', to='nyuuustead.Hug'),
        ),
    ]
