# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nyuuustead', '0009_auto_20160707_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userware',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='hug',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
