# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyuuustead', '0010_auto_20160707_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='userware',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='_userware_following_+', to='nyuuustead.Userware'),
        ),
    ]
