# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyuuustead', '0011_userware_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userware',
            name='daily_notifications',
            field=models.BooleanField(default=True, help_text='Those will be sent to your email no more often than once a day, at 13:37 server time.'),
        ),
        migrations.AlterField(
            model_name='userware',
            name='hourly_notifications',
            field=models.BooleanField(default=False, help_text='Those will be sent to your email no more often than once per hour.'),
        ),
        migrations.AlterField(
            model_name='userware',
            name='news_emails',
            field=models.BooleanField(default=True, help_text="Those will be sent whenever I have something to announce, which probably won't be too often."),
        ),
    ]
