# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyuuustead', '0012_auto_20160708_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='hugkind',
            name='verb',
            field=models.CharField(db_index=True, default='test', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hugkind',
            name='verb_tercery',
            field=models.CharField(default='tests', max_length=20),
            preserve_default=False,
        ),
    ]
