# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyuuustead', '0013_auto_20160708_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userware',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='_userware_following_+', to='nyuuustead.Userware'),
        ),
    ]
