# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyuuustead', '0014_auto_20160708_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='userware',
            name='hugs_to_notify',
            field=models.ManyToManyField(blank=True, to='nyuuustead.Hug'),
        ),
    ]
