# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyuuustead', '0015_userware_hugs_to_notify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userware',
            name='following',
        ),
        migrations.AddField(
            model_name='userware',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_userware_followers_+', to='nyuuustead.Userware'),
        ),
    ]
